/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'triloksaig' at '2/15/19 4:09 PM' with Gradle 2.14.1
 *
 * @author triloksaig, @date 2/15/19 4:09 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
